# Generated by Django 4.2.20 on 2025-06-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageStorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
