# Generated by Django 4.2.20 on 2025-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageStorage', '0002_alter_imagefile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
