# Generated by Django 4.2.20 on 2025-06-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageStorage', '0003_alter_imagefile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='image',
            new_name='img',
        ),
    ]
